# Generated by Django 4.2 on 2023-04-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_products_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.CharField(default=True, max_length=1024),
        ),
    ]
